/**
 * Copyright (c) 2015-2016, Michael Yang 杨福海 (fuhai999@gmail.com).
 *
 * Licensed under the GNU Lesser General Public License (LGPL) ,Version 3.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.gnu.org/licenses/lgpl-3.0.txt
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.abreaking.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;
import com.abreaking.model.Metadata;
import com.abreaking.model.core.JModel;
import com.abreaking.model.query.MetaDataQuery;

import java.math.BigInteger;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTaxonomy<M extends BaseTaxonomy<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "taxonomy";
	public static final String METADATA_TYPE = "taxonomy";

	public void removeCache(Object key){
		if(key == null) return;
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	public Metadata createMetadata(){
		Metadata md = new Metadata();
		md.setObjectId(getId());
		md.setObjectType(METADATA_TYPE);
		return md;
	}

	public Metadata createMetadata(String key,String value){
		Metadata md = new Metadata();
		md.setObjectId(getId());
		md.setObjectType(METADATA_TYPE);
		md.setMetaKey(key);
		md.setMetaValue(value);
		return md;
	}

	public boolean saveOrUpdateMetadta(String key,String value){
		Metadata metadata = MetaDataQuery.me().findByTypeAndIdAndKey(METADATA_TYPE, getId(), key);
		if (metadata == null) {
			metadata = createMetadata(key, value);
			return metadata.save();
		}
		metadata.setMetaValue(value);
		return metadata.update();
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseTaxonomy<?>)){return false;}

		BaseTaxonomy<?> m = (BaseTaxonomy<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	public void setId(BigInteger id) {
		set("id", id);
	}

	public BigInteger getId() {
		Object id = get("id");
		if (id == null)
			return null;

		return id instanceof BigInteger ? (BigInteger)id : new BigInteger(id.toString());
	}

	public void setTitle(String title) {
		set("title", title);
	}

	public String getTitle() {
		return get("title");
	}

	public void setText(String text) {
		set("text", text);
	}

	public String getText() {
		return get("text");
	}

	public void setSlug(String slug) {
		set("slug", slug);
	}

	public String getSlug() {
		return get("slug");
	}

	public void setType(String type) {
		set("type", type);
	}

	public String getType() {
		return get("type");
	}

	public void setIcon(String icon) {
		set("icon", icon);
	}

	public String getIcon() {
		return get("icon");
	}

	public void setContentModule(String contentModule) {
		set("content_module", contentModule);
	}

	public String getContentModule() {
		return get("content_module");
	}

	public void setContentCount(Long contentCount) {
		set("content_count", contentCount);
	}

	public Long getContentCount() {
		return get("content_count");
	}

	public void setOrderNumber(Integer orderNumber) {
		set("order_number", orderNumber);
	}

	public Integer getOrderNumber() {
		return get("order_number");
	}

	public void setParentId(BigInteger parentId) {
		set("parent_id", parentId);
	}

	public BigInteger getParentId() {
		return get("parent_id");
	}

	public void setObjectId(BigInteger objectId) {
		set("object_id", objectId);
	}

	public BigInteger getObjectId() {
		return get("object_id");
	}

	public void setFlag(String flag) {
		set("flag", flag);
	}

	public String getFlag() {
		return get("flag");
	}

	public void setLat(java.math.BigDecimal lat) {
		set("lat", lat);
	}

	public java.math.BigDecimal getLat() {
		return get("lat");
	}

	public void setLng(java.math.BigDecimal lng) {
		set("lng", lng);
	}

	public java.math.BigDecimal getLng() {
		return get("lng");
	}

	public void setMetaKeywords(String metaKeywords) {
		set("meta_keywords", metaKeywords);
	}

	public String getMetaKeywords() {
		return get("meta_keywords");
	}

	public void setMetaDescription(String metaDescription) {
		set("meta_description", metaDescription);
	}

	public String getMetaDescription() {
		return get("meta_description");
	}

	public void setCreated(java.util.Date created) {
		set("created", created);
	}

	public java.util.Date getCreated() {
		return get("created");
	}

}
